title: SPAN Lab
email: npatwari@wustl.edu
description: >
  The Sensing, People, and Networks (SPAN) Lab at the <a
  href="https://www.wustl.edu">Washington University in St. Louis</a>  
  conducts research on two topics: wireless networking, and the equity of engineered
  and automated sensing and decision systems. We have a history of augmenting the
  reliability, efficiency, and capabilities of networks using the radio as a sensing
  interface in addition to the communication interface.  We also investigate how 
  sensing and other "big data" systems and algorithms that affect the resources 
  people are allocated can have both positive and negative effects on equity in society. 
  Students in the SPAN Lab study wireless networking, statistical signal processing, and 
  power and inequity, and these tools enable us to study the 
  interaction of people, networks, and sensing systems in new ways that will 
  lead to greater privacy, reliability, and equity of engineered systems.

baseurl: "https://span.engineering.wustl.edu"
url: https://span.engineering.wustl.edu

markdown: kramdown
